services:

  db:
    image: postgres:18

    container_name: DividirParaMultiplicar_db

    restart: always

    env_file: 
      - .env
  
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  web:
    build: .
    container_name: DividirParaMultiplicar_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    
volumes:
  postgres_data: